using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GenerateSampleTruth
{
    public class CodonTable
    {
        public static Dictionary<string, string> TheTable = new Dictionary<string, string>
        {
            {"TTT", "F"},
            {"TTC", "F"},
            {"TTA", "L"},
            {"TTG", "L"},
            {"CTT", "L"},
            {"CTC", "L"},
            {"CTA", "L"},
            {"CTG", "L"},
            {"ATT", "I"},
            {"ATC", "I"},
            {"ATA", "I"},
            {"ATG", "M"},
            {"GTT", "V"},
            {"GTC", "V"},
            {"GTA", "V"},
            {"GTG", "V"},
            {"TCT", "S"},
            {"TCC", "S"},
            {"TCA", "S"},
            {"TCG", "S"},
            {"CCT", "P"},
            {"CCC", "P"},
            {"CCA", "P"},
            {"CCG", "P"},
            {"ACT", "T"},
            {"ACC", "T"},
            {"ACA", "T"},
            {"ACG", "T"},
            {"GCT", "A"},
            {"GCC", "A"},
            {"GCA", "A"},
            {"GCG", "A"},
            {"TAT", "Y"},
            {"TAC", "Y"},
            {"TAA", "X"},
            {"TAG", "X"},
            {"CAT", "H"},
            {"CAC", "H"},
            {"CAA", "Q"},
            {"CAG", "Q"},
            {"AAT", "N"},
            {"AAC", "N"},
            {"AAA", "K"},
            {"AAG", "K"},
            {"GAT", "D"},
            {"GAC", "D"},
            {"GAA", "E"},
            {"GAG", "E"},
            {"TGT", "C"},
            {"TGC", "C"},
            {"TGA", "X"},
            {"TGG", "W"},
            {"CGT", "R"},
            {"CGC", "R"},
            {"CGA", "R"},
            {"CGG", "R"},
            {"AGT", "S"},
            {"AGC", "S"},
            {"AGA", "R"},
            {"AGG", "R"},
            {"GGT", "G"},
            {"GGC", "G"},
            {"GGA", "G"},
            {"GGG", "G"},
        };

        public static Dictionary<string, string> OneToThreeLetterLookup = new Dictionary<string, string>
        {
            {"F", "Phe"},
            {"L", "Leu"},
            {"I", "Ile"},
            {"M", "Met"},
            {"V", "Val"},
            {"S", "Ser"},
            {"T", "Thr"},
            {"B", "Asx"},
            {"A", "Ala"},
            {"Y", "Tyr"},
            {"P", "Pro"},
            {"H", "His"},
            {"Q", "Gln"},
            {"N", "Asn"},
            {"K", "Lys"},
            {"D", "Asp"},
            {"E", "Glu"},
            {"C", "Cys"},
            {"X", "Xaa"},
            {"W", "Trp"},
            {"R", "Arg"},
            {"G", "Gly"},
            {"Z", "Glx"},
        };
    }
}
